
package com.example.demoapplication.ui.WebService.ws;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAXWS SI.
 * JAX-WS RI 2.0_02-b08-fcs
 * Generated source version: 2.0
 * 
 */
@WebService(name = "datainput", targetNamespace = "http://webservice.jd.com/")
public interface Datainput {


    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "query", targetNamespace = "http://webservice.jd.com/", className = "com.jd.webservice.Query")
    @ResponseWrapper(localName = "queryResponse", targetNamespace = "http://webservice.jd.com/", className = "com.jd.webservice.QueryResponse")
    public String query(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

    /**
     * 
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "others", targetNamespace = "http://webservice.jd.com/", className = "com.jd.webservice.Others")
    @ResponseWrapper(localName = "othersResponse", targetNamespace = "http://webservice.jd.com/", className = "com.jd.webservice.OthersResponse")
    public String others();

}
